-- AlterTable Supplier
ALTER TABLE "Supplier" ADD COLUMN "profilePhotoUrl" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "gender" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "province" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "cell" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "village" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "ageRange" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "fieldType" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "pastCropsSeason1" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "pastCropsSeason2" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "pastCropsSeason3" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "currentCrop" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "chemicalsPerWeek" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "chemicalsWhy" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "chemicalsDosage" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "fertilizerPerWeek" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "irrigationMethod" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "diseasesIdentified" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "pestsIdentified" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "totalQuantityHarvested" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "qualityGeneral" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "priceUnit" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "pricePerUnit" INTEGER;
ALTER TABLE "Supplier" ADD COLUMN "totalKgsBoughtByHuza" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "Supplier" ADD COLUMN "paymentOption" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "farmGatePrice" INTEGER;
ALTER TABLE "Supplier" ADD COLUMN "priceUponDelivery" INTEGER;
ALTER TABLE "Supplier" ADD COLUMN "priceAfterSale" INTEGER;
ALTER TABLE "Supplier" ADD COLUMN "proofOfPaymentUrl" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "farmerComments" TEXT;

-- AlterTable Product
ALTER TABLE "Product" ADD COLUMN "reviewStatus" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "Product" ADD COLUMN "reviewNote" TEXT;
ALTER TABLE "Product" ADD COLUMN "reviewedAt" TIMESTAMP(3);
ALTER TABLE "Product" ADD COLUMN "fieldType" TEXT;
ALTER TABLE "Product" ADD COLUMN "fieldSize" TEXT;
ALTER TABLE "Product" ADD COLUMN "pastCropsSeason1" TEXT;
ALTER TABLE "Product" ADD COLUMN "pastCropsSeason2" TEXT;
ALTER TABLE "Product" ADD COLUMN "pastCropsSeason3" TEXT;
ALTER TABLE "Product" ADD COLUMN "currentCrop" TEXT;
ALTER TABLE "Product" ADD COLUMN "chemicalsPerWeek" TEXT;
ALTER TABLE "Product" ADD COLUMN "chemicalsWhy" TEXT;
ALTER TABLE "Product" ADD COLUMN "chemicalsDosage" TEXT;
ALTER TABLE "Product" ADD COLUMN "fertilizerPerWeek" TEXT;
ALTER TABLE "Product" ADD COLUMN "irrigationMethod" TEXT;
ALTER TABLE "Product" ADD COLUMN "diseasesIdentified" TEXT;
ALTER TABLE "Product" ADD COLUMN "pestsIdentified" TEXT;
ALTER TABLE "Product" ADD COLUMN "totalQuantityHarvested" TEXT;
ALTER TABLE "Product" ADD COLUMN "qualityGeneral" TEXT;
ALTER TABLE "Product" ADD COLUMN "priceUnit" TEXT;
ALTER TABLE "Product" ADD COLUMN "pricePerUnit" INTEGER;
ALTER TABLE "Product" ADD COLUMN "totalKgsBoughtByHuza" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "Product" ADD COLUMN "paymentOption" TEXT;
ALTER TABLE "Product" ADD COLUMN "farmGatePrice" INTEGER;
ALTER TABLE "Product" ADD COLUMN "priceUponDelivery" INTEGER;
ALTER TABLE "Product" ADD COLUMN "priceAfterSale" INTEGER;
ALTER TABLE "Product" ADD COLUMN "proofOfPaymentUrl" TEXT;
ALTER TABLE "Product" ADD COLUMN "farmerComments" TEXT;
