/**
 * HUZA FRESH catalog — Kigali mid/high retail reference prices (RWF, 2026).
 * Sources: Kigali newcomers cost index + typical café/ready-to-eat pricing.
 * Images live in /public/images/catalog/
 */

export type CatalogProductSeed = {
  slug: string;
  category: string;
  nameEn: string;
  nameFr: string;
  nameRw: string;
  descriptionEn: string;
  descriptionFr: string;
  descriptionRw: string;
  price: number;
  unit: "KG" | "PIECE" | "BUNCH" | "LITRE" | "PACK" | "DOZEN";
  stockQty: number;
  originDistrict: string;
  image: string;
  keywords: string;
  isOrganic?: boolean;
  isFeatured?: boolean;
  isBestSeller?: boolean;
  isNewArrival?: boolean;
};

export const CATALOG_CATEGORIES = [
  {
    slug: "fresh-fruits",
    nameEn: "Fresh Fruits",
    nameFr: "Fruits frais",
    nameRw: "Imbuto nshya",
    sortOrder: 1,
    image: "/images/catalog/cat-fruits.jpg",
  },
  {
    slug: "fresh-vegetables",
    nameEn: "Fresh Vegetables",
    nameFr: "Légumes frais",
    nameRw: "Imboga nshya",
    sortOrder: 2,
    image: "/images/catalog/cat-vegetables.jpg",
  },
  {
    slug: "fruit-seedlings",
    nameEn: "Fruit Seedlings",
    nameFr: "Plants fruitiers",
    nameRw: "Imbuto z'ibiti",
    sortOrder: 3,
    image: "/images/catalog/cat-seedlings.jpg",
  },
  {
    slug: "ornamental-plants",
    nameEn: "Ornamental Plants",
    nameFr: "Plantes ornementales",
    nameRw: "Ibimera byo gutunganya",
    sortOrder: 4,
    image: "/images/catalog/cat-ornamental.jpg",
  },
  {
    slug: "fruit-salads",
    nameEn: "Fruit Salads",
    nameFr: "Salades de fruits",
    nameRw: "Insalade z'imbuto",
    sortOrder: 5,
    image: "/images/catalog/cat-salads.jpg",
  },
  {
    slug: "fresh-juices",
    nameEn: "Fresh Juices",
    nameFr: "Jus frais",
    nameRw: "Amacunga mashya",
    sortOrder: 6,
    image: "/images/catalog/cat-juices.jpg",
  },
] as const;

export const CATALOG_PRODUCTS: CatalogProductSeed[] = [
  // ——— Fresh fruits (Kigali retail) ———
  {
    slug: "sweet-bananas",
    category: "fresh-fruits",
    nameEn: "Sweet Bananas",
    nameFr: "Bananes douces",
    nameRw: "Ibitoki boryoha",
    descriptionEn: "Sweet dessert bananas — popular everyday fruit across Kigali.",
    descriptionFr: "Bananes dessert douces — fruit quotidien populaire à Kigali.",
    descriptionRw: "Ibitoki boryoha — imbuto zikoreshwa buri munsi i Kigali.",
    price: 850,
    unit: "KG",
    stockQty: 120,
    originDistrict: "Kayonza",
    image: "/images/catalog/bananas.jpg",
    keywords: "banana sweet dessert fruit",
    isBestSeller: true,
    isFeatured: true,
  },
  {
    slug: "fresh-avocados",
    category: "fresh-fruits",
    nameEn: "Fresh Avocados",
    nameFr: "Avocats frais",
    nameRw: "Avoka nshya",
    descriptionEn: "Large creamy avocados. Sold by piece at typical Kigali retail size.",
    descriptionFr: "Gros avocats crémeux. Vendus à la pièce (taille retail Kigali).",
    descriptionRw: "Avoka nini nziza. Zigurishwa ku gice.",
    price: 400,
    unit: "PIECE",
    stockQty: 200,
    originDistrict: "Musanze",
    image: "/images/catalog/avocado.jpg",
    keywords: "avocado hass cream fruit",
    isOrganic: true,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    slug: "passion-fruit",
    category: "fresh-fruits",
    nameEn: "Passion Fruit",
    nameFr: "Fruit de la passion",
    nameRw: "Marakuja",
    descriptionEn: "Aromatic passion fruit for juice and desserts.",
    descriptionFr: "Fruit de la passion aromatique pour jus et desserts.",
    descriptionRw: "Marakuja nziza ku juice n'ibinyamutso.",
    price: 2200,
    unit: "KG",
    stockQty: 70,
    originDistrict: "Nyagatare",
    image: "/images/catalog/passion-fruit.jpg",
    keywords: "passion maracuja juice fruit",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    slug: "sweet-pineapple",
    category: "fresh-fruits",
    nameEn: "Sweet Pineapple",
    nameFr: "Ananas sucré",
    nameRw: "Inanasi iryoha",
    descriptionEn: "Large juicy pineapple — ready to slice or juice.",
    descriptionFr: "Grand ananas juteux — prêt à couper ou presser.",
    descriptionRw: "Inanasi nini iryoha — yiteguye gucibwa cyangwa ku juice.",
    price: 1200,
    unit: "PIECE",
    stockQty: 90,
    originDistrict: "Bugesera",
    image: "/images/catalog/pineapple.jpg",
    keywords: "pineapple ananas fruit",
    isFeatured: true,
    isNewArrival: true,
  },
  {
    slug: "ripe-mangoes",
    category: "fresh-fruits",
    nameEn: "Ripe Mangoes",
    nameFr: "Mangues mûres",
    nameRw: "Amyembe yizeye",
    descriptionEn: "Seasonal ripe mangoes — sweet and ready to eat.",
    descriptionFr: "Mangues de saison mûres — sucrées et prêtes à manger.",
    descriptionRw: "Amyembe y'igihe yizeye — araryoha.",
    price: 2500,
    unit: "KG",
    stockQty: 55,
    originDistrict: "Kayonza",
    image: "/images/catalog/mango.jpg",
    keywords: "mango seasonal fruit",
    isBestSeller: true,
  },
  {
    slug: "fresh-papaya",
    category: "fresh-fruits",
    nameEn: "Fresh Papaya",
    nameFr: "Papaye fraîche",
    nameRw: "Ipapayi nshya",
    descriptionEn: "Soft ripe papaya for breakfast bowls and salads.",
    descriptionFr: "Papaye mûre pour bols du matin et salades.",
    descriptionRw: "Ipapayi yizeye ku breakfast n'insalade.",
    price: 1500,
    unit: "PIECE",
    stockQty: 60,
    originDistrict: "Nyagatare",
    image: "/images/catalog/papaya.jpg",
    keywords: "papaya pawpaw fruit",
    isNewArrival: true,
  },
  {
    slug: "tree-tomato",
    category: "fresh-fruits",
    nameEn: "Tree Tomato",
    nameFr: "Tamarillo",
    nameRw: "Ibinyomoro",
    descriptionEn: "Local tree tomato (tamarillo) — great for juice.",
    descriptionFr: "Tamarillo local — excellent pour le jus.",
    descriptionRw: "Ibinyomoro byo mu gihugu — byiza ku juice.",
    price: 1800,
    unit: "KG",
    stockQty: 40,
    originDistrict: "Musanze",
    image: "/images/catalog/tree-tomato.jpg",
    keywords: "tree tomato tamarillo juice",
  },
  {
    slug: "watermelon",
    category: "fresh-fruits",
    nameEn: "Watermelon",
    nameFr: "Pastèque",
    nameRw: "Pasteke",
    descriptionEn: "Large refreshing watermelon — shared family size.",
    descriptionFr: "Grande pastèque rafraîchissante — taille familiale.",
    descriptionRw: "Pasteke nini — ku muryango.",
    price: 4500,
    unit: "PIECE",
    stockQty: 25,
    originDistrict: "Bugesera",
    image: "/images/catalog/watermelon.jpg",
    keywords: "watermelon melon fruit",
  },
  {
    slug: "oranges",
    category: "fresh-fruits",
    nameEn: "Oranges",
    nameFr: "Oranges",
    nameRw: "Amacunga",
    descriptionEn: "Juicy oranges — bag-equivalent retail pricing for citrus.",
    descriptionFr: "Oranges juteuses.",
    descriptionRw: "Amacunga aryoha.",
    price: 2000,
    unit: "KG",
    stockQty: 50,
    originDistrict: "Rwamagana",
    image: "/images/catalog/oranges.jpg",
    keywords: "orange citrus fruit",
  },
  {
    slug: "lemons",
    category: "fresh-fruits",
    nameEn: "Lemons",
    nameFr: "Citrons",
    nameRw: "Indimu",
    descriptionEn: "Fresh lemons — pack of about 5 at typical Kigali retail.",
    descriptionFr: "Citrons frais — sachet d’environ 5 (prix Kigali).",
    descriptionRw: "Indimu nshya — isakoshi cyangwa ~5.",
    price: 1000,
    unit: "PACK",
    stockQty: 80,
    originDistrict: "Rwamagana",
    image: "/images/catalog/lemons.jpg",
    keywords: "lemon citrus",
  },
  {
    slug: "guava",
    category: "fresh-fruits",
    nameEn: "Guava",
    nameFr: "Goyave",
    nameRw: "Amapera",
    descriptionEn: "Sweet local guavas when in season.",
    descriptionFr: "Goyaves locales sucrées en saison.",
    descriptionRw: "Amapera yo mu gihugu yoryoha.",
    price: 1600,
    unit: "KG",
    stockQty: 35,
    originDistrict: "Kamonyi",
    image: "/images/catalog/guava.jpg",
    keywords: "guava fruit",
  },

  // ——— Fresh vegetables ———
  {
    slug: "fresh-tomatoes",
    category: "fresh-vegetables",
    nameEn: "Fresh Tomatoes",
    nameFr: "Tomates fraîches",
    nameRw: "Inyanya nshya",
    descriptionEn: "Ripe red tomatoes for sauces and salads.",
    descriptionFr: "Tomates rouges mûres pour sauces et salades.",
    descriptionRw: "Inyanya zitukura ziza ku sauce n'insalade.",
    price: 1300,
    unit: "KG",
    stockQty: 150,
    originDistrict: "Bugesera",
    image: "/images/catalog/tomato.jpg",
    keywords: "tomato salad sauce vegetable",
    isBestSeller: true,
    isFeatured: true,
  },
  {
    slug: "red-onions",
    category: "fresh-vegetables",
    nameEn: "Red Onions",
    nameFr: "Oignons rouges",
    nameRw: "Ibungura bitukura",
    descriptionEn: "Red onions for everyday cooking.",
    descriptionFr: "Oignons rouges pour la cuisine quotidienne.",
    descriptionRw: "Ibungura bitukura byo guteka buri munsi.",
    price: 1450,
    unit: "KG",
    stockQty: 100,
    originDistrict: "Rubavu",
    image: "/images/catalog/onions.jpg",
    keywords: "onion red vegetable",
    isBestSeller: true,
  },
  {
    slug: "white-onions",
    category: "fresh-vegetables",
    nameEn: "White Onions",
    nameFr: "Oignons blancs",
    nameRw: "Ibungura byera",
    descriptionEn: "White onions — mild flavour for salads and stews.",
    descriptionFr: "Oignons blancs — goût doux.",
    descriptionRw: "Ibungura byera.",
    price: 1800,
    unit: "KG",
    stockQty: 70,
    originDistrict: "Rubavu",
    image: "/images/catalog/onions.jpg",
    keywords: "onion white vegetable",
  },
  {
    slug: "irish-potatoes",
    category: "fresh-vegetables",
    nameEn: "Irish Potatoes",
    nameFr: "Pommes de terre",
    nameRw: "Ibirayi",
    descriptionEn: "Premium Irish potatoes for chips and stews.",
    descriptionFr: "Pommes de terre premium pour frites et ragoûts.",
    descriptionRw: "Ibirayi byiza ku chips n'isosi.",
    price: 750,
    unit: "KG",
    stockQty: 200,
    originDistrict: "Musanze",
    image: "/images/catalog/irish-potatoes.jpg",
    keywords: "potato irish vegetable",
    isBestSeller: true,
  },
  {
    slug: "sweet-potatoes",
    category: "fresh-vegetables",
    nameEn: "Sweet Potatoes",
    nameFr: "Patates douces",
    nameRw: "Ibijumba",
    descriptionEn: "Local sweet potatoes — staple comfort food.",
    descriptionFr: "Patates douces locales.",
    descriptionRw: "Ibijumba byo mu gihugu.",
    price: 600,
    unit: "KG",
    stockQty: 160,
    originDistrict: "Kamonyi",
    image: "/images/catalog/sweet-potatoes.jpg",
    keywords: "sweet potato vegetable",
  },
  {
    slug: "carrots",
    category: "fresh-vegetables",
    nameEn: "Carrots",
    nameFr: "Carottes",
    nameRw: "Karoti",
    descriptionEn: "Crisp fresh carrots with greens.",
    descriptionFr: "Carottes croquantes fraîches.",
    descriptionRw: "Karoti nshya.",
    price: 1100,
    unit: "KG",
    stockQty: 90,
    originDistrict: "Rubavu",
    image: "/images/catalog/carrots.jpg",
    keywords: "carrot vegetable",
    isFeatured: true,
  },
  {
    slug: "green-cabbage",
    category: "fresh-vegetables",
    nameEn: "Green Cabbage",
    nameFr: "Chou vert",
    nameRw: "Amashu",
    descriptionEn: "Fresh cabbage heads from highland farms.",
    descriptionFr: "Choux frais des fermes de montagne.",
    descriptionRw: "Amashu mashya ava mu misozi.",
    price: 800,
    unit: "PIECE",
    stockQty: 80,
    originDistrict: "Musanze",
    image: "/images/catalog/cabbage.jpg",
    keywords: "cabbage vegetable",
    isOrganic: true,
  },
  {
    slug: "green-peppers",
    category: "fresh-vegetables",
    nameEn: "Green Bell Peppers",
    nameFr: "Poivrons verts",
    nameRw: "Puwavuro y'icyatsi",
    descriptionEn: "Crisp green peppers for stir-fries and salads.",
    descriptionFr: "Poivrons verts croquants.",
    descriptionRw: "Puwavuro y'icyatsi.",
    price: 1500,
    unit: "KG",
    stockQty: 45,
    originDistrict: "Bugesera",
    image: "/images/catalog/green-peppers.jpg",
    keywords: "pepper capsicum vegetable",
  },
  {
    slug: "cucumber",
    category: "fresh-vegetables",
    nameEn: "Cucumber",
    nameFr: "Concombre",
    nameRw: "Konkombre",
    descriptionEn: "Fresh cucumber — priced per piece.",
    descriptionFr: "Concombre frais — à la pièce.",
    descriptionRw: "Konkombre nshya — ku gice.",
    price: 500,
    unit: "PIECE",
    stockQty: 100,
    originDistrict: "Kamonyi",
    image: "/images/catalog/cucumber.jpg",
    keywords: "cucumber vegetable salad",
  },
  {
    slug: "spinach-bunch",
    category: "fresh-vegetables",
    nameEn: "Spinach",
    nameFr: "Épinards",
    nameRw: "Epinari",
    descriptionEn: "Large fresh spinach bunch.",
    descriptionFr: "Gros bouquet d’épinards frais.",
    descriptionRw: "Epinari nshya.",
    price: 500,
    unit: "BUNCH",
    stockQty: 60,
    originDistrict: "Gasabo",
    image: "/images/catalog/spinach.jpg",
    keywords: "spinach leafy green",
    isNewArrival: true,
  },
  {
    slug: "amaranth-dodo",
    category: "fresh-vegetables",
    nameEn: "Amaranth (Dodo)",
    nameFr: "Amarante (Dodo)",
    nameRw: "Dodo",
    descriptionEn: "Popular Rwandan leafy green — sold by the bunch.",
    descriptionFr: "Légume-feuille rwandais populaire — au bouquet.",
    descriptionRw: "Dodo — imboga zikunzwe mu Rwanda.",
    price: 400,
    unit: "BUNCH",
    stockQty: 70,
    originDistrict: "Gasabo",
    image: "/images/catalog/amaranth.jpg",
    keywords: "amaranth dodo leafy",
    isBestSeller: true,
  },
  {
    slug: "broccoli",
    category: "fresh-vegetables",
    nameEn: "Broccoli",
    nameFr: "Brocoli",
    nameRw: "Broccoli",
    descriptionEn: "Fresh broccoli head.",
    descriptionFr: "Tête de brocoli fraîche.",
    descriptionRw: "Broccoli nshya.",
    price: 1500,
    unit: "PIECE",
    stockQty: 30,
    originDistrict: "Musanze",
    image: "/images/catalog/broccoli.jpg",
    keywords: "broccoli vegetable",
  },
  {
    slug: "french-beans",
    category: "fresh-vegetables",
    nameEn: "French Beans",
    nameFr: "Haricots verts",
    nameRw: "Ibishyimbo byatsi",
    descriptionEn: "Tender French beans — 500g pack equivalent pricing.",
    descriptionFr: "Haricots verts tendres — prix équivalent 500 g.",
    descriptionRw: "Ibishyimbo byatsi byoroshye.",
    price: 800,
    unit: "PACK",
    stockQty: 40,
    originDistrict: "Nyagatare",
    image: "/images/catalog/french-beans.jpg",
    keywords: "french beans green beans",
  },
  {
    slug: "garlic-net",
    category: "fresh-vegetables",
    nameEn: "Garlic",
    nameFr: "Ail",
    nameRw: "Tungurusumu",
    descriptionEn: "Garlic net ~250g — Kigali retail pack.",
    descriptionFr: "Filet d’ail ~250 g.",
    descriptionRw: "Tungurusumu ~250g.",
    price: 1200,
    unit: "PACK",
    stockQty: 55,
    originDistrict: "Rubavu",
    image: "/images/catalog/garlic.jpg",
    keywords: "garlic spice vegetable",
  },
  {
    slug: "fresh-chili",
    category: "fresh-vegetables",
    nameEn: "Fresh Chili",
    nameFr: "Piment frais",
    nameRw: "Urusenda",
    descriptionEn: "Hot fresh chili — small bag retail.",
    descriptionFr: "Piment frais — petit sachet.",
    descriptionRw: "Urusenda rushya.",
    price: 300,
    unit: "PACK",
    stockQty: 90,
    originDistrict: "Kamonyi",
    image: "/images/catalog/chili.jpg",
    keywords: "chili pepper hot",
  },

  // ——— Fruit seedlings ———
  {
    slug: "avocado-seedling",
    category: "fruit-seedlings",
    nameEn: "Avocado Seedling",
    nameFr: "Plant d’avocatier",
    nameRw: "Ikiti cy'avoka",
    descriptionEn: "Healthy avocado seedling in nursery pot.",
    descriptionFr: "Plant d’avocatier sain en pot.",
    descriptionRw: "Ikiti cy'avoka gikora neza.",
    price: 5000,
    unit: "PIECE",
    stockQty: 40,
    originDistrict: "Musanze",
    image: "/images/catalog/avocado-seedling.jpg",
    keywords: "seedling avocado nursery",
    isFeatured: true,
  },
  {
    slug: "passion-seedling",
    category: "fruit-seedlings",
    nameEn: "Passion Fruit Seedling",
    nameFr: "Plant de maracuja",
    nameRw: "Ikiti cya marakuja",
    descriptionEn: "Passion fruit vine seedling for home gardens.",
    descriptionFr: "Plant de fruit de la passion pour jardins.",
    descriptionRw: "Ikiti cya marakuja ku mirima y'urugo.",
    price: 3500,
    unit: "PIECE",
    stockQty: 50,
    originDistrict: "Nyagatare",
    image: "/images/catalog/passion-seedling.jpg",
    keywords: "seedling passion vine",
    isBestSeller: true,
  },
  {
    slug: "mango-seedling",
    category: "fruit-seedlings",
    nameEn: "Mango Seedling",
    nameFr: "Plant de manguier",
    nameRw: "Ikiti cy'umwembe",
    descriptionEn: "Mango tree seedling — grafted where available.",
    descriptionFr: "Plant de manguier.",
    descriptionRw: "Ikiti cy'umwembe.",
    price: 4500,
    unit: "PIECE",
    stockQty: 35,
    originDistrict: "Kayonza",
    image: "/images/catalog/mango-seedling.jpg",
    keywords: "seedling mango tree",
  },
  {
    slug: "tree-tomato-seedling",
    category: "fruit-seedlings",
    nameEn: "Tree Tomato Seedling",
    nameFr: "Plant de tamarillo",
    nameRw: "Ikiti cy'ibinyomoro",
    descriptionEn: "Tree tomato (tamarillo) seedling.",
    descriptionFr: "Plant de tamarillo.",
    descriptionRw: "Ikiti cy'ibinyomoro.",
    price: 3000,
    unit: "PIECE",
    stockQty: 40,
    originDistrict: "Musanze",
    image: "/images/catalog/passion-seedling.jpg",
    keywords: "seedling tamarillo",
  },
  {
    slug: "banana-sucker",
    category: "fruit-seedlings",
    nameEn: "Banana Sucker",
    nameFr: "Rejet de bananier",
    nameRw: "Umwana w'igitoki",
    descriptionEn: "Healthy banana planting sucker.",
    descriptionFr: "Rejet de bananier sain.",
    descriptionRw: "Umwana w'igitoki ukora neza.",
    price: 2000,
    unit: "PIECE",
    stockQty: 60,
    originDistrict: "Kayonza",
    image: "/images/catalog/bananas.jpg",
    keywords: "banana sucker seedling",
    isNewArrival: true,
  },
  {
    slug: "citrus-seedling",
    category: "fruit-seedlings",
    nameEn: "Orange Seedling",
    nameFr: "Plant d’oranger",
    nameRw: "Ikiti cy'amacunga",
    descriptionEn: "Orange / citrus seedling for gardens.",
    descriptionFr: "Plant d’agrumes.",
    descriptionRw: "Ikiti cy'amacunga.",
    price: 4000,
    unit: "PIECE",
    stockQty: 30,
    originDistrict: "Rwamagana",
    image: "/images/catalog/oranges.jpg",
    keywords: "orange citrus seedling",
  },

  // ——— Ornamental plants ———
  {
    slug: "hibiscus-plant",
    category: "ornamental-plants",
    nameEn: "Hibiscus Plant",
    nameFr: "Hibiscus",
    nameRw: "Hibiscus",
    descriptionEn: "Flowering hibiscus in decorative pot.",
    descriptionFr: "Hibiscus fleuri en pot décoratif.",
    descriptionRw: "Hibiscus mu nkono nziza.",
    price: 8000,
    unit: "PIECE",
    stockQty: 25,
    originDistrict: "Gasabo",
    image: "/images/catalog/hibiscus.jpg",
    keywords: "hibiscus flower ornamental",
    isFeatured: true,
  },
  {
    slug: "bougainvillea",
    category: "ornamental-plants",
    nameEn: "Bougainvillea",
    nameFr: "Bougainvillier",
    nameRw: "Bougainvillea",
    descriptionEn: "Colourful bougainvillea for gardens and gates.",
    descriptionFr: "Bougainvillier coloré pour jardins.",
    descriptionRw: "Bougainvillea z'amabara.",
    price: 7000,
    unit: "PIECE",
    stockQty: 20,
    originDistrict: "Gasabo",
    image: "/images/catalog/ornamental-plant.jpg",
    keywords: "bougainvillea ornamental",
    isBestSeller: true,
  },
  {
    slug: "aloe-vera",
    category: "ornamental-plants",
    nameEn: "Aloe Vera",
    nameFr: "Aloe vera",
    nameRw: "Aloe vera",
    descriptionEn: "Healthy aloe vera pot plant.",
    descriptionFr: "Aloe vera en pot.",
    descriptionRw: "Aloe vera mu nkono.",
    price: 3500,
    unit: "PIECE",
    stockQty: 40,
    originDistrict: "Kicukiro",
    image: "/images/catalog/ornamental-plant.jpg",
    keywords: "aloe ornamental indoor",
  },
  {
    slug: "money-plant",
    category: "ornamental-plants",
    nameEn: "Money Plant",
    nameFr: "Plante monétaire",
    nameRw: "Money plant",
    descriptionEn: "Easy indoor money plant (pothos).",
    descriptionFr: "Plante d’intérieur facile (pothos).",
    descriptionRw: "Ikimeera cyo mu nzu.",
    price: 4000,
    unit: "PIECE",
    stockQty: 35,
    originDistrict: "Kicukiro",
    image: "/images/catalog/ornamental-plant.jpg",
    keywords: "pothos money plant indoor",
    isNewArrival: true,
  },
  {
    slug: "snake-plant",
    category: "ornamental-plants",
    nameEn: "Snake Plant",
    nameFr: "Sansevieria",
    nameRw: "Snake plant",
    descriptionEn: "Low-maintenance snake plant for offices and homes.",
    descriptionFr: "Sansevieria facile d’entretien.",
    descriptionRw: "Ikimeera cyoroshye.",
    price: 5500,
    unit: "PIECE",
    stockQty: 28,
    originDistrict: "Gasabo",
    image: "/images/catalog/ornamental-plant.jpg",
    keywords: "snake plant sansevieria",
  },
  {
    slug: "rose-plant",
    category: "ornamental-plants",
    nameEn: "Rose Plant",
    nameFr: "Rosier",
    nameRw: "Amarozi",
    descriptionEn: "Potted rose plant for gifts and gardens.",
    descriptionFr: "Rosier en pot.",
    descriptionRw: "Amarozi mu nkono.",
    price: 9000,
    unit: "PIECE",
    stockQty: 18,
    originDistrict: "Musanze",
    image: "/images/catalog/hibiscus.jpg",
    keywords: "rose ornamental gift",
  },

  // ——— Fruit salads (café/retail ready-to-eat) ———
  {
    slug: "tropical-fruit-salad",
    category: "fruit-salads",
    nameEn: "Tropical Fruit Salad",
    nameFr: "Salade tropicale",
    nameRw: "Insalade y'imbuto",
    descriptionEn: "Pineapple, papaya and mango — ready to eat cup.",
    descriptionFr: "Ananas, papaye et mangue — coupe prête à manger.",
    descriptionRw: "Inanasi, ipapayi n'amyembe — byiteguye kurya.",
    price: 3500,
    unit: "PACK",
    stockQty: 40,
    originDistrict: "Kigali",
    image: "/images/catalog/fruit-salad-cup.jpg",
    keywords: "salad tropical ready eat",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    slug: "pineapple-salad",
    category: "fruit-salads",
    nameEn: "Pineapple Salad",
    nameFr: "Salade d’ananas",
    nameRw: "Insalade y'inanasi",
    descriptionEn: "Fresh diced pineapple cup.",
    descriptionFr: "Coupe d’ananas frais.",
    descriptionRw: "Inanasi zicate.",
    price: 2500,
    unit: "PACK",
    stockQty: 45,
    originDistrict: "Kigali",
    image: "/images/catalog/fruit-salad.jpg",
    keywords: "pineapple salad cup",
  },
  {
    slug: "passion-pineapple-salad",
    category: "fruit-salads",
    nameEn: "Passion & Pineapple Salad",
    nameFr: "Salade passion-ananas",
    nameRw: "Marakuja n'inanasi",
    descriptionEn: "Passion fruit with pineapple — bright and tangy.",
    descriptionFr: "Passion et ananas — frais et acidulé.",
    descriptionRw: "Marakuja n'inanasi.",
    price: 3800,
    unit: "PACK",
    stockQty: 30,
    originDistrict: "Kigali",
    image: "/images/catalog/fruit-salad-cup.jpg",
    keywords: "passion pineapple salad",
    isNewArrival: true,
  },
  {
    slug: "family-fruit-tray",
    category: "fruit-salads",
    nameEn: "Family Fruit Tray",
    nameFr: "Plateau familial de fruits",
    nameRw: "Ikibindi cy'imbuto",
    descriptionEn: "Large mixed fruit tray for sharing.",
    descriptionFr: "Grand plateau de fruits mixtes.",
    descriptionRw: "Imbuto nyinshi zo gusangira.",
    price: 9000,
    unit: "PACK",
    stockQty: 15,
    originDistrict: "Kigali",
    image: "/images/catalog/fruit-salad.jpg",
    keywords: "family tray salad party",
  },

  // ——— Fresh juices ———
  {
    slug: "passion-juice",
    category: "fresh-juices",
    nameEn: "Passion Fruit Juice",
    nameFr: "Jus de maracuja",
    nameRw: "Juice ya marakuja",
    descriptionEn: "Fresh pressed passion juice — chilled bottle.",
    descriptionFr: "Jus de passion pressé — bouteille fraîche.",
    descriptionRw: "Juice ya marakuja ikonje.",
    price: 2500,
    unit: "LITRE",
    stockQty: 50,
    originDistrict: "Kigali",
    image: "/images/catalog/passion-juice.jpg",
    keywords: "juice passion fresh",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    slug: "pineapple-juice",
    category: "fresh-juices",
    nameEn: "Pineapple Juice",
    nameFr: "Jus d’ananas",
    nameRw: "Juice y'inanasi",
    descriptionEn: "Fresh pineapple juice — no concentrate.",
    descriptionFr: "Jus d’ananas frais.",
    descriptionRw: "Juice y'inanasi nshya.",
    price: 2200,
    unit: "LITRE",
    stockQty: 45,
    originDistrict: "Kigali",
    image: "/images/catalog/pineapple-juice.jpg",
    keywords: "juice pineapple",
  },
  {
    slug: "pineapple-ginger-juice",
    category: "fresh-juices",
    nameEn: "Pineapple Ginger Juice",
    nameFr: "Jus ananas-gingembre",
    nameRw: "Juice y'inanasi n'inginge",
    descriptionEn: "Kigali favourite blend — pineapple with ginger kick.",
    descriptionFr: "Mélange préféré — ananas et gingembre.",
    descriptionRw: "Juice yakunzwe — inanasi n'inginge.",
    price: 2800,
    unit: "LITRE",
    stockQty: 40,
    originDistrict: "Kigali",
    image: "/images/catalog/pineapple-juice.jpg",
    keywords: "pineapple ginger juice blend",
    isBestSeller: true,
  },
  {
    slug: "mango-juice",
    category: "fresh-juices",
    nameEn: "Mango Juice",
    nameFr: "Jus de mangue",
    nameRw: "Juice y'amyembe",
    descriptionEn: "Thick sweet mango juice when mangoes are in season.",
    descriptionFr: "Jus de mangue épais et sucré.",
    descriptionRw: "Juice y'amyembe iryoha.",
    price: 2500,
    unit: "LITRE",
    stockQty: 35,
    originDistrict: "Kigali",
    image: "/images/catalog/orange-juice.jpg",
    keywords: "mango juice",
  },
  {
    slug: "tree-tomato-juice",
    category: "fresh-juices",
    nameEn: "Tree Tomato Juice",
    nameFr: "Jus de tamarillo",
    nameRw: "Juice y'ibinyomoro",
    descriptionEn: "Local tree tomato juice — vitamin-rich favourite.",
    descriptionFr: "Jus de tamarillo local.",
    descriptionRw: "Juice y'ibinyomoro.",
    price: 2300,
    unit: "LITRE",
    stockQty: 35,
    originDistrict: "Kigali",
    image: "/images/catalog/orange-juice.jpg",
    keywords: "tree tomato juice tamarillo",
    isNewArrival: true,
  },
  {
    slug: "sugarcane-juice",
    category: "fresh-juices",
    nameEn: "Sugarcane Juice",
    nameFr: "Jus de canne",
    nameRw: "Juice y'ibigori",
    descriptionEn: "Fresh pressed sugarcane juice — cup/bottle retail.",
    descriptionFr: "Jus de canne pressé.",
    descriptionRw: "Juice y'ibigori ikonze.",
    price: 1500,
    unit: "PACK",
    stockQty: 40,
    originDistrict: "Kigali",
    image: "/images/catalog/passion-juice.jpg",
    keywords: "sugarcane juice",
  },
];
