-- Align Role enum with schema (MANAGER, INVENTORY, FINANCE were in schema but never migrated)
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'INVENTORY';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FINANCE';
